//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    public enum EResType
    {
        /// <summary>
        /// 货币
        /// </summary>
        Money = 0,
        /// <summary>
        /// 水
        /// </summary>
        Water = 1,
        /// <summary>
        /// 能量
        /// </summary>
        Power = 2,
        /// <summary>
        /// 建筑材料
        /// </summary>
        BuildingRes = 3,
        /// <summary>
        /// 幼苗
        /// </summary>
        Seedling = 4,
    }
}
