//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    [System.Flags]
    public enum EBuildingType
    {
        /// <summary>
        /// 功能建筑
        /// </summary>
        Functional = 1,
        /// <summary>
        /// 生产建筑
        /// </summary>
        Production = 2,
        /// <summary>
        /// 仓储建筑
        /// </summary>
        Storage = 4,
        /// <summary>
        /// 治沙建筑
        /// </summary>
        SandCtrl = 8,
    }

} 
