//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    public enum EResType
    {
        /// <summary>
        /// 任意类型
        /// </summary>
        Any = 0,
        /// <summary>
        /// 货币
        /// </summary>
        Money = 1,
        /// <summary>
        /// 水
        /// </summary>
        Water = 2,
        /// <summary>
        /// 电力
        /// </summary>
        Electricity = 3,
        /// <summary>
        /// 建筑材料
        /// </summary>
        BuildingMaterial = 4,
        /// <summary>
        /// 幼苗
        /// </summary>
        Seedling = 5,
    }

} 
