//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.MapSystem
{

public sealed partial class BlockElementConfig :  Bright.Config.BeanBase 
{
    public BlockElementConfig(JSONNode _json) 
    {
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["generateRate"].IsNumber) { throw new SerializationException(); }  GenerateRate = _json["generateRate"]; }
        { if(!_json["numRange"].IsNumber) { throw new SerializationException(); }  NumRange = _json["numRange"]; }
        { if(!_json["modelPath"].IsString) { throw new SerializationException(); }  ModelPath = _json["modelPath"]; }
        { if(!_json["materialPath"].IsString) { throw new SerializationException(); }  MaterialPath = _json["materialPath"]; }
        PostInit();
    }

    public BlockElementConfig(string name, float generateRate, int numRange, string modelPath, string materialPath ) 
    {
        this.Name = name;
        this.GenerateRate = generateRate;
        this.NumRange = numRange;
        this.ModelPath = modelPath;
        this.MaterialPath = materialPath;
        PostInit();
    }

    public static BlockElementConfig DeserializeBlockElementConfig(JSONNode _json)
    {
        return new MapSystem.BlockElementConfig(_json);
    }

    /// <summary>
    /// 元素名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 生成概率
    /// </summary>
    public float GenerateRate { get; private set; }
    /// <summary>
    /// 每地块数量范围
    /// </summary>
    public int NumRange { get; private set; }
    /// <summary>
    /// 模型路径
    /// </summary>
    public string ModelPath { get; private set; }
    /// <summary>
    /// 材质路径
    /// </summary>
    public string MaterialPath { get; private set; }

    public const int __ID__ = 1264361012;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "GenerateRate:" + GenerateRate + ","
        + "NumRange:" + NumRange + ","
        + "ModelPath:" + ModelPath + ","
        + "MaterialPath:" + MaterialPath + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
