//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.MapSystem
{

public sealed partial class DTBlockConfig
{
    private readonly Dictionary<int, MapSystem.BlockConfig> _dataMap;
    private readonly List<MapSystem.BlockConfig> _dataList;
    
    public DTBlockConfig(JSONNode _json)
    {
        _dataMap = new Dictionary<int, MapSystem.BlockConfig>();
        _dataList = new List<MapSystem.BlockConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = MapSystem.BlockConfig.DeserializeBlockConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, MapSystem.BlockConfig> DataMap => _dataMap;
    public List<MapSystem.BlockConfig> DataList => _dataList;

    public MapSystem.BlockConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MapSystem.BlockConfig Get(int key) => _dataMap[key];
    public MapSystem.BlockConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}