//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.MapSystem
{
    public enum EBlockType
    {
        /// <summary>
        /// 沙漠
        /// </summary>
        Desert = 0,
        /// <summary>
        /// 戈壁
        /// </summary>
        Gobi = 1,
        /// <summary>
        /// 绿洲
        /// </summary>
        Oasis = 2,
    }
}
